LOCAL_PATH := $(call my-dir)

CORE_DIR  := $(LOCAL_PATH)/..

SOURCES_C :=

include $(CORE_DIR)/Makefile.common

COREFLAGS := -DANDROID -DRETRO -DAND -D__LIBRETRO__ -DALIGN_DWORD $(CFLAGS)  $(INCFLAGS) -I$(LOCAL_PATH)/include
COREFLAGS += -DCPUEMU_0 -DCPUEMU_11 -DCPUEMU_12 -DCPUEMU_20 -DCPUEMU_21 -DCPUEMU_22  -DFPUEMU -DUNALIGNED_PROFITABLE -DAMAX -DAGA -DAUTOCONFIG -DFILESYS -DSUPPORT_THREADS  -DFDI2RAW -DDEBUGGER -DSAVESTATE -DACTION_REPLAY -DCPUEMU_31 -DCPUEMU_32  -DCPUEMU_33 -DMMUEMU -DFULLMMU -DDRIVESOUND

GIT_VERSION := " $(shell git rev-parse --short HEAD || echo unknown)"
ifneq ($(GIT_VERSION)," unknown")
  COREFLAGS += -DGIT_VERSION=\"$(GIT_VERSION)\"
endif

include $(CLEAR_VARS)
LOCAL_MODULE    := retro
LOCAL_SRC_FILES := $(SOURCES_C)
LOCAL_CFLAGS    := -std=c99 $(COREFLAGS)
LOCAL_LDFLAGS   := -Wl,-version-script=$(CORE_DIR)/libretro/link.T
LOCAL_LDLIBS    := -lz
LOCAL_DISABLE_FORMAT_STRING_CHECKS := true
LOCAL_ARM_MODE     := arm
include $(BUILD_SHARED_LIBRARY)
