task:
  name: FreeBSD (shortest)
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0
      image_family: freebsd-12-2
  install_script: pkg install -y gmake coreutils
  script: |
    MOREFLAGS="-Werror" gmake -j all
    gmake shortest
